name: API CI/CD
defaults:
  run:
    working-directory: api

on:
  push:
    paths:
      - api/**
      - .github/workflows/api-ci-cd.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: "12"
          distribution: "adopt"
      - name: Run Unit Tests
        run: ./gradlew test

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: "12"
          distribution: "adopt"
      - name: Run Kotlin Linter
        run: ./gradlew detekt

  deploy:
    runs-on: ubuntu-latest
    needs: [test, linter]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build API
        run: gcloud builds submit --tag gcr.io/cody-engel-landing/api .
      - name: Deploy API
        run: gcloud run deploy api --image gcr.io/cody-engel-landing/api --platform managed --region us-central1
